/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/terii/Laptop.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Lap(props) {
  const { nodes, materials } = useGLTF('./model/terii/Laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.091, 0]}>
        <mesh geometry={nodes.Box20255_1.geometry} material={materials._crayfishdiffuse} />
        <mesh geometry={nodes.Box20255_1_1.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Box20255_1_2.geometry} material={materials['03___Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/terii/Laptop.glb')
